DEVSTORE_ACCOUNT = "itng"
DEVSTORE_SECRET_KEY = "lB7IwQE02zX40aXkHS6ZnBwKSrIcDDlgLI20svI6nqeOJ1FUaYZNYGoC7tDxxXUXz2haRDkIYNAezEOGFo51gQ==" 
 
DEVSTORE_BLOB_HOST = "127.0.0.1:10000"
DEVSTORE_TABLE_HOST = "127.0.0.1:10002"
 
CLOUD_BLOB_HOST = "blob.core.windows.net"
CLOUD_TABLE_HOST = "table.core.windows.net"

GOOGLE_CONSUMER_KEY = 'opus-dev.cnl.ncsu.edu'
GOOGLE_CONSUMER_SECRET = 'rPWrZkWdKBP8+OJGqbKwBWSE'
