from django.conf.urls.defaults import *

urlpatterns = patterns('dataview.views',
    url(r'^googletest/$', 'google_test'),
    url(r'^$', 'dataview_home',name='dataview-home'),
    url(r'^backend/$', 'data_backend'),
    url(r'^backend/all/$','list_backends'),
    url(r'^backend/google/$','google_backend',name='google-backend-form'),
    url(r'^backend/azure/$','azure_backend',name='azure-backend-form'),
    url(r'^backend/google/(?P<be_pk>(\d)+)/$','google_backend',name='edit-google-backend-form'),
    url(r'^backend/azure/(?P<be_pk>(\d)+)/$','azure_backend',name='edit-azure-backend-form'),
    url(r'^dataview/$','dataview',name='dataview-form'),
    url(r'^dataview/all/$','list_dataviews'),
    url(r'^dataview/(?P<dv_pk>(\d)+)/$','dataview',name='edit-dataview-form'),
    url(r'^dataview/(?P<dv_pk>(\d)+)/visualization$','dataview_visualizations'),
    url(r'^visualization/$','visualization',name='visualization-form'),
    url(r'^visualization/all/$','list_visualizations'),
    url(r'^visualization/(?P<viz_pk>(\d)+)/$','visualization',name='edit-visualization-form'),
    url(r'^visualization/(?P<viz_pk>(\d)+)/chart/$','chart',name='chart'),
    url(r'^data/(?P<dv_pk>(\d)+)/$','viz_data_source',name='datasource'),
    (r'^tables/$','list_tables'),
    (r'^(?P<table_name>\w+)/(?P<row_key>\w*)/(?P<partition_key>\w*)/$','get_entry'),
    (r'^(?P<table_name>\w+)/$', 'check_request_type'),
)
